### ISSUE TITLE
'any' type in TournamentController

### ISSUE THREAD

**Issue by billbarni** [OysteinAmundsen/gymsystems#233]
Methods `addToList `and `removeFromList `in `TournamentController.ts` have implicit any types.

Lines 359, 373 and 374:
`tournament['type']`

**Comment by OysteinAmundsen** [comment]
Once again a nice catch. Thank you for testing the system. 
I don't actually remember at the moment why I did this. I have to test a bit more before I fix this.

**Comment by OysteinAmundsen** [comment]
Those methods where a work in progress. I commented them away for the 1.0.2 release.
