### ISSUE TITLE
Client build fails for several reasons

### ISSUE THREAD

**Issue by billbarni** [OysteinAmundsen/gymsystems#234]
in `package.json`, the `typescript` package version should be updated to at least '2.6.1' or an error occurs when building the client app. The error is commented here:

https://github.com/angular/angular-cli/issues/7110

`npm install typescript@latest --save` (or any 2.6.x version) solves the issue, but a warning will appear when building the app.

For now I think that a warning is better then an error.

All `'rxjs/Rx'` imports must be changed to `'rxjs/ObjectName'`. Eg.: `import { Observable } from 'rxjs/Observable';`

`hammerjs`, `hammer-timejs` and `@types/hammerjs` must also be included in `package.json`.

`snyk protect` also throws an error, being unable to fix an issue with `marked` package (I tried running `snyk wizard` but it also threw me an error).
I removed the `marked `package since I did not find it used anywhere, maybe I`m wrong and being a bad developer as I am, I could not find how to remove this packages automagically.

Sorry if I'm not already creating git updates with the changes, no knowledge of Git.

If I'm bothering you opening this issues, please tell me. I'm just trying to help while learning some code.

**Comment by OysteinAmundsen** [comment]
No need to apologize at all. Nice to see that someone is showing an interest in this project. :-) And a second set of eyes on the code is of great help. For that, I thank you. 

If you want to help with coding, you are welcome to. You state that you don't know git, but it's fairly simple. You can fork the project (top right corner of github). This will create a copy of this repo on your github user. On this copy, create changes, commit & push. Then you can apply for a "pull request" on this repo based on your changes. This will collect and package your changes, and mark them as ready for merge. If the unit tests pass, I will then review the changes and merge them in if I agree.

**Comment by OysteinAmundsen** [comment]
Ok, so by importing directly from rxjs/<subpackage> instead of through the Rx bundle, made it difficult for webpack to tie Observable operands to the Observable namespace. I was forced to rollback this. 

Don't know which errors you are experiencing, but I need to deploy whatever both Travis CI and docker-cloud accepts as buildable.

**Comment by billbarni** [comment]
No errors. Both server and client are building/running fine. But don't bother with this, I will try to have it working on my fork and you can take a look.
