### ISSUE TITLE
Delete operations needs a confirmation dialog

### ISSUE THREAD

**Issue by OysteinAmundsen** [OysteinAmundsen/gymsystems#604]
**Is your feature request related to a problem? Please describe.**
As removing data from the system is a destructive operation which cannot be recovered, users should confirm the operation.

**Describe the solution you'd like**
A confirmation dialog should pop up explaining to the user that the operation is non-recoverable and asking if this is something they truly want. Removal should also be constrained to top level users and creators of the data.

**Comment by ConnectNitish** [comment]
I would like to take this opportunity . I will start with the installation steps.

**Comment by OysteinAmundsen** [comment]
Really appreciate you wanting to help out here @ConnectNitish . But please pick from any of the other issues here. This issue is already resolved with the previous commit.
